services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: x86lab
    tty: true
    stdin_open: true
    working_dir: /root
    volumes:
      - .:/work
      - x86lab-root:/root

volumes:
  x86lab-root:
